name: android-macOS
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: make init
    - run: make demo
    - run: make build
    - uses: actions/upload-artifact@v2
      with:
        name: heapsapp-debug.apk
        path: heaps-android-app/heapsapp/build/outputs/apk/debug/heapsapp-debug.apk
